//
// Bonus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Bonus: Codable {

    public let count: Int64?
    public let reward: ModelInt?

    public init(count: Int64? = nil, reward: ModelInt? = nil) {
        self.count = count
        self.reward = reward
    }


}
