//
// Coin.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** NOTE: The amount field is an Int which implements the custom method signatures required by gogoproto. */

public struct Coin: Codable {

    public var amount: ModelInt?
    public var denom: String?

    public init(amount: ModelInt? = nil, denom: String? = nil) {
        self.amount = amount
        self.denom = denom
    }


}
