//
// ConfirmRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ConfirmRequest: Codable {

    public let code: String?
    public let email: String?

    public init(code: String? = nil, email: String? = nil) {
        self.code = code
        self.email = email
    }


}
