//
// ReferralCodeResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReferralCodeResponse: Codable {

    public var code: String?

    public init(code: String? = nil) {
        self.code = code
    }


}
