//
// RegisterRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RegisterRequest: Codable {

    public var address: String?
    public var email: String
    public var recaptchaResponse: String?
    public var referralCode: String?

    public init(address: String? = nil, email: String, recaptchaResponse: String? = nil, referralCode: String? = nil) {
        self.address = address
        self.email = email
        self.recaptchaResponse = recaptchaResponse
        self.referralCode = referralCode
    }


}
