//
// RewardLevel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RewardLevel: Codable {

    public let from: Int64?
    public let reward: ModelInt?
    public let to: Int64?

    public init(from: Int64? = nil, reward: ModelInt? = nil, to: Int64? = nil) {
        self.from = from
        self.reward = reward
        self.to = to
    }


}
