//
// StatsItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Date is RFC3999 date, value is number of new accounts. */

public extension VulcanAPI {
    
    struct StatsItem: Codable {
        
        public var date: String?
        public var value: Int64?
        
        public init(date: String? = nil, value: Int64? = nil) {
            self.date = date
            self.value = value
        }
        
        
    }
    
}
