//
// StatsItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Key is RFC3999 date, value is PDV. */

public extension DcntrAPI {
    
    struct StatsItem: Codable {
        
        public let date: String?
        public let value: Double?
        
        public init(date: String? = nil, value: Double? = nil) {
            self.date = date
            self.value = value
        }
        
        
    }
    
}
