//
// DecentrStats.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DecentrStats: Codable {

    public let adv: Double?
    public let ddv: Double?

    public init(adv: Double? = nil, ddv: Double? = nil) {
        self.adv = adv
        self.ddv = ddv
    }


}
