//
// GetPostResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetPostResponse: Codable {

    public let post: Post?
    public let profileStats: ProfileStats?
    public let stats: [DcntrAPI.StatsItem]?

    public init(post: Post? = nil, profileStats: ProfileStats? = nil, stats: [DcntrAPI.StatsItem]? = nil) {
        self.post = post
        self.profileStats = profileStats
        self.stats = stats
    }


}
