//
// ListPostsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ListPostsResponse: Codable {

    public var posts: [Post]?
    /** ProfileStats contains profiles stats. */
    public var profileStats: [String:ProfileStats]?
    /** Posts&#x27; statistics dictionary where key is a full form ID (owner/uuid) and value is statistics */
    public var stats: [String:[DcntrAPI.StatsItem]]?

    public init(posts: [Post]? = nil, profileStats: [String:ProfileStats]? = nil, stats: [String:[DcntrAPI.StatsItem]]? = nil) {
        self.posts = posts
        self.profileStats = profileStats
        self.stats = stats
    }


}
