//
// Post.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Post: Codable {

    public let category: Category?
    public let createdAt: Int?
    public let dislikesCount: Int?
    public let likeWeight: LikeWeight?
    public let likesCount: Int?
    public let owner: String?
    public let pdv: Double?
    public let previewImage: String?
    public let slug: String?
    public let text: String?
    public let title: String?
    public let uuid: String?

    public init(category: Category? = nil, createdAt: Int? = nil, dislikesCount: Int? = nil, likeWeight: LikeWeight? = nil, likesCount: Int? = nil, owner: String? = nil, pdv: Double? = nil, previewImage: String? = nil, slug: String? = nil, text: String? = nil, title: String? = nil, uuid: String? = nil) {
        self.category = category
        self.createdAt = createdAt
        self.dislikesCount = dislikesCount
        self.likeWeight = likeWeight
        self.likesCount = likesCount
        self.owner = owner
        self.pdv = pdv
        self.previewImage = previewImage
        self.slug = slug
        self.text = text
        self.title = title
        self.uuid = uuid
    }


}
