//
// Post.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Post: Codable {

    public var category: Category?
    public var createdAt: Int?
    public var dislikesCount: Int?
    public var likeWeight: LikeWeight?
    public var likesCount: Int?
    public var owner: String?
    public var pdv: Double?
    public var previewImage: String?
    public var slug: String?
    public var text: String?
    public var title: String?
    public var uuid: String?

    public init(category: Category? = nil, createdAt: Int? = nil, dislikesCount: Int? = nil, likeWeight: LikeWeight? = nil, likesCount: Int? = nil, owner: String? = nil, pdv: Double? = nil, previewImage: String? = nil, slug: String? = nil, text: String? = nil, title: String? = nil, uuid: String? = nil) {
        self.category = category
        self.createdAt = createdAt
        self.dislikesCount = dislikesCount
        self.likeWeight = likeWeight
        self.likesCount = likesCount
        self.owner = owner
        self.pdv = pdv
        self.previewImage = previewImage
        self.slug = slug
        self.text = text
        self.title = title
        self.uuid = uuid
    }


}
