//
// ProfileStats.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProfileStats: Codable {

    public var postsCount: Int?
    public var stats: [DcntrAPI.StatsItem]?

    public init(postsCount: Int? = nil, stats: [DcntrAPI.StatsItem]? = nil) {
        self.postsCount = postsCount
        self.stats = stats
    }


}
