//
// ImageAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


public extension CerberusAPI.ImageAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    class func save(completion: @escaping ((_ data: SaveImageResponse?,_ error: Error?) -> Void)) {
        saveWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /images

     - API Key:
       - type: apiKey Public-Key 
       - name: public_key
     - API Key:
       - type: apiKey Signature 
       - name: signature
     - examples: [{contentType=application/json, example={
  "thumb" : "thumb",
  "hd" : "hd"
}}]

     - returns: RequestBuilder<SaveImageResponse> 
     */
    class func saveWithRequestBuilder() -> RequestBuilder<SaveImageResponse> {
        let path = "/v1/images"
        let URLString = CerberusAPI.Data.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<SaveImageResponse>.Type = CerberusAPI.Data.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", path: path, URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
