//
// ProfileAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


public extension CerberusAPI.ProfileAPI {
    /**
     Get profiles

     - parameter address: (query) profile address 
     - parameter completion: completion handler to receive the data and the error objects
     */
    class func getProfiles(address: Any, completion: @escaping ((_ data: [APIProfile]?,_ error: Error?) -> Void)) {
        getProfilesWithRequestBuilder(address: address).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get profiles
     - GET /profiles

     - examples: [{contentType=application/json, example=[ {
  "birthday" : "birthday",
  "emails" : [ "emails", "emails" ],
  "createdAt" : 0,
  "firstName" : "firstName",
  "lastName" : "lastName",
  "address" : "address",
  "gender" : "gender",
  "bio" : "bio",
  "avatar" : "avatar",
  "banned" : true
}, {
  "birthday" : "birthday",
  "emails" : [ "emails", "emails" ],
  "createdAt" : 0,
  "firstName" : "firstName",
  "lastName" : "lastName",
  "address" : "address",
  "gender" : "gender",
  "bio" : "bio",
  "avatar" : "avatar",
  "banned" : true
} ]}]
     - parameter address: (query) profile address 

     - returns: RequestBuilder<[APIProfile]> 
     */
    class func getProfilesWithRequestBuilder(address: Any) -> RequestBuilder<[APIProfile]> {
        let path = "/profiles"
        let URLString = CerberusAPI.Data.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "address": address
        ])


        let requestBuilder: RequestBuilder<[APIProfile]>.Type = CerberusAPI.Data.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
