//
// ProfilesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


public extension TheseusAPI.ProfilesAPI {
    /**
     Returns decentr stats.

     - parameter completion: completion handler to receive the data and the error objects
     */
    class func getDecentrStats(completion: @escaping ((_ data: DecentrStats?,_ error: Error?) -> Void)) {
        getDecentrStatsWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Returns decentr stats.
     - GET /profiles/stats
     - 

     - examples: [{contentType=application/json, example={
  "adv" : 0.8008281904610115,
  "ddv" : 6.027456183070403
}}]

     - returns: RequestBuilder<DecentrStats> 
     */
    class func getDecentrStatsWithRequestBuilder() -> RequestBuilder<DecentrStats> {
        let path = "/profiles/stats"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<DecentrStats>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Get pdv stats by address.

     - parameter address: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    class func getProfileStats(address: String, completion: @escaping ((_ data: ProfileStats?,_ error: Error?) -> Void)) {
        getProfileStatsWithRequestBuilder(address: address).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get pdv stats by address.
     - GET /profiles/{address}/stats
     - 

     - examples: [{contentType=application/json, example={
  "postsCount" : 7,
  "stats" : [ {
    "date" : "date",
    "value" : 9.301444243932576
  }, {
    "date" : "date",
    "value" : 9.301444243932576
  } ]
}}]
     - parameter address: (path)  

     - returns: RequestBuilder<ProfileStats> 
     */
    class func getProfileStatsWithRequestBuilder(address: String) -> RequestBuilder<ProfileStats> {
        var path = "/profiles/{address}/stats"
        let addressPreEscape = "\(address)"
        let addressPostEscape = addressPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{address}", with: addressPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ProfileStats>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
