//
// GetPostResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetPostResponse: Codable {

    public var post: Post?
    public var profileStats: ProfileStats?
    public var stats: [TheseusAPI.StatsItem]?

    public init(post: Post? = nil, profileStats: ProfileStats? = nil, stats: [TheseusAPI.StatsItem]? = nil) {
        self.post = post
        self.profileStats = profileStats
        self.stats = stats
    }


}
