//
// SharePost.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SharePost: Codable {

    public var owner: String?
    public var title: String?
    public var uuid: String?

    public init(owner: String? = nil, title: String? = nil, uuid: String? = nil) {
        self.owner = owner
        self.title = title
        self.uuid = uuid
    }


}
