//
// APIProfile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct APIProfile: Codable {

    public let address: String?
    public let avatar: String?
    public let banned: Bool?
    public let bio: String?
    public let birthday: String? //"1986-03-09"
    public let createdAt: Int64? //1644319784
    public let emails: [String]?
    public let firstName: String?
    public let gender: String? //"male"
    public let lastName: String?

    public init(address: String? = nil, avatar: String? = nil, banned: Bool? = nil, bio: String? = nil, birthday: String? = nil, createdAt: Int64? = nil, emails: [String]? = nil, firstName: String? = nil, gender: String? = nil, lastName: String? = nil) {
        self.address = address
        self.avatar = avatar
        self.banned = banned
        self.bio = bio
        self.birthday = birthday
        self.createdAt = createdAt
        self.emails = emails
        self.firstName = firstName
        self.gender = gender
        self.lastName = lastName
    }


}
