//
// Blacklist.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Blacklist: Codable {

    public var cookieSource: [String]?

    public init(cookieSource: [String]? = nil) {
        self.cookieSource = cookieSource
    }


}
