//
// Location.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Location: Codable {

    public enum ModelType: String, Codable { 
        case advertiserid = "advertiserId"
        case cookie = "cookie"
        case profile = "profile"
        case searchhistory = "searchHistory"
        case location = "location"
    }
    public var type: ModelType?
    public var latitude: Double?
    public var longitude: Double?
    public var requestedBy: Source?
    public var timestamp: Date?

    public init(type: ModelType? = nil, latitude: Double? = nil, longitude: Double? = nil, requestedBy: Source? = nil, timestamp: Date? = nil) {
        self.type = type
        self.latitude = latitude
        self.longitude = longitude
        self.requestedBy = requestedBy
        self.timestamp = timestamp
    }


}
