//
// PDVMeta.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PDVMeta: Codable {

    public var objectTypes: ObjectTypes?
    public var reward: Int?

    public init(objectTypes: ObjectTypes? = nil, reward: Int? = nil) {
        self.objectTypes = objectTypes
        self.reward = reward
    }

    public enum CodingKeys: String, CodingKey { 
        case objectTypes = "object_types"
        case reward
    }

}
