//
// PDVRewardsPool.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PDVRewardsPool: Codable {

    public var nextDistributionDate: Date?
    public var size: Dec?
    public var totalDelta: Dec?

    public init(nextDistributionDate: Date? = nil, size: Dec? = nil, totalDelta: Dec? = nil) {
        self.nextDistributionDate = nextDistributionDate
        self.size = size
        self.totalDelta = totalDelta
    }

    public enum CodingKeys: String, CodingKey { 
        case nextDistributionDate = "next_distribution_date"
        case size
        case totalDelta = "total_delta"
    }

}
