//
// PDVRewardDelta.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PDVRewardDelta: Codable {

    public var delta: Dec?
    public var pool: PDVRewardsPool?

    public init(delta: Dec? = nil, pool: PDVRewardsPool? = nil) {
        self.delta = delta
        self.pool = pool
    }


}
