//
// SavePDVResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SavePDVResponse: Codable {

    public var _id: Int?

    public init(_id: Int? = nil) {
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
    }

}
