//
// SaveImageResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SaveImageResponse: Codable {

    public let hd: String?
    public let thumb: String?

    public init(hd: String? = nil, thumb: String? = nil) {
        self.hd = hd
        self.thumb = thumb
    }


}
