//
// SearchHistory.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchHistory: Codable {

    public enum ModelType: String, Codable { 
        case advertiserid = "advertiserId"
        case cookie = "cookie"
        case profile = "profile"
        case searchhistory = "searchHistory"
        case location = "location"
    }
    public let type: ModelType?
    public let domain: String?
    public let engine: String?
    public let query: String?
    public let timestamp: Date?

    public init(type: ModelType? = nil, domain: String? = nil, engine: String? = nil, query: String? = nil, timestamp: Date? = nil) {
        self.type = type
        self.domain = domain
        self.engine = engine
        self.query = query
        self.timestamp = timestamp
    }


}
