//
// Source.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Source: Codable {

    /** Domain of website where object was taken */
    public var host: String?
    /** Path of website&#x27;s url where object was taken */
    public var path: String?

    public init(host: String? = nil, path: String? = nil) {
        self.host = host
        self.path = path
    }


}
