//
// Timestamp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Timestamp: Codable {

    public let timestamp: Date?

    public init(timestamp: Date? = nil) {
        self.timestamp = timestamp
    }


}
