//
// Dec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** NOTE: never use new(Dec) or else we will panic unmarshalling into the nil embedded big.Int */

public struct Dec: Codable {




}
