//
// ModelError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ModelError: Codable {

    public let error: String?

    public init(error: String? = nil) {
        self.error = error
    }


}
